version: "3.3"
services:

  php:
    build: .
    restart: unless-stopped
    container_name: guest-portal_php
    volumes:
      - "./:/var/www"
    env_file:
      - mysql.env
      - unifi.env

  nginx:
    image: nginx
    restart: unless-stopped
    container_name: guest-portal_nginx
    user: nginx
    volumes:
      - "./resources/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./:/var/www:ro"
    read_only: true
    tmpfs:
      - /tmp
    ports:
      - "8080:8080"

  db:
    image: linuxserver/mariadb:alpine
    restart: unless-stopped
    container_name: guest-portal_db
    volumes:
      - "mysql:/var/lib/mysql"
      - "./resources/db-template.sql:/config/initdb.d/db.sql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    env_file:
      - mysql.env

volumes:
  mysql:
