version: "3.3"
services:

  php:
    build: .
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: guest-portal
      MYSQL_PASSWORD: guest-portal
      MYSQL_DATABASE: guest-portal
      UNIFI_USER: guest-portal
      UNIFI_PASSWORD: password
      UNIFI_URL: https://192.168.0.1
      UNIFI_SITE: default
      UNIFI_VERSION: 6.0.43
      UNIFI_VERIFY_CERT: 0
    volumes:
      - "./:/var/www:ro"

  nginx:
    image: nginx
    restart: unless-stopped
    user: nginx
    volumes:
      - "./resources/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./:/var/www:ro"
    read_only: true
    tmpfs:
      - /tmp
    ports:
      - "8080:8080"

  db:
    image: linuxserver/mariadb:alpine
    volumes:
      - mysql:/var/lib/mysql
      - ./resources/db-template.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: guest-portal
      MYSQL_PASSWORD: guest-portal
      MYSQL_DATABASE: guest-portal

volumes:
  mysql:
