version: "3.3"
services:

  backend:
    build:
      dockerfile: Docker/Backend.docker
      context: .
    restart: unless-stopped
    volumes:
      - "./:/var/www"
    env_file:
      - mysql.env
      - unifi.env

  frontend:
    build:
      dockerfile: Docker/Frontend.docker
      context: .
    restart: unless-stopped
    user: nginx
    volumes:
      - "./resources/nginx.conf:/etc/nginx/nginx.conf:ro"
    read_only: true
    tmpfs:
      - /tmp
    ports:
      - "8080:8080"

  database:
    image: linuxserver/mariadb:alpine
    restart: unless-stopped
    volumes:
      - "mysql:/var/lib/mysql"
      - "./resources/db-template.sql:/config/initdb.d/db.sql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    env_file:
      - mysql.env

volumes:
  mysql:
