version: "3.7"
services:

  backend:
    build:
      dockerfile: Docker/Backend.docker
      context: .
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    env_file:
      - mysql.env
      - unifi.env
    networks:
      - php
      - mysql

  frontend:
    build:
      dockerfile: Docker/Frontend.docker
      context: .
    restart: unless-stopped
    volumes:
      - "./resources/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./resources/images/:/guest-portal/public/img/bg/:ro"
    read_only: true
    tmpfs:
      - /tmp
    ports:
      - "8080:8080"
    networks:
      - php

  database:
    image: linuxserver/mariadb:latest
    volumes:
      - "mysql:/var/lib/mysql"
      - "./resources/db-template.sql:/config/initdb.d/db.sql"
    env_file:
      - mysql.env
    networks:
      - mysql

networks:
  mysql:
  php:
volumes:
  mysql:
