name: Docker Push
on:
  release:
    types: published
jobs:
  Build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: crazy-max/ghaction-docker-buildx@v3
       with:
         buildx-version: latest
         qemu-version: latest
     - name: Docker build
       run: |
         echo "${{ secrets.DOCKER }}" | docker login --username carlgo11 --password-stdin
         docker buildx create --use
         VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
         # Strip "v" prefix from tag name
         [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
         echo VERSION=$VERSION
         docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 --rm --tag carlgo11/guest-portal:latest --tag carlgo11/guest-portal:$VERSION --push --compress .
