name: Publish Released Images

on:
  release:
    types: [ published ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Backend metadata
        id: backend-meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ GITHUB.REPOSITORY }}
            ghcr.io/${{ GITHUB.REPOSITORY }}
          tags: |
            type=raw,value=backend
            type=semver,pattern={{version}},prefix=backend-
            type=semver,pattern={{major}}.{{minor}},prefix=backend-
            type=semver,pattern={{major}},prefix=backend-
          flavor: |
            latest=false

      - name: Docker Frontend metadata
        id: frontend-meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ GITHUB.REPOSITORY }}
            ghcr.io/${{ GITHUB.REPOSITORY }}
          tags: |
            type=raw,value=frontend
            type=semver,pattern={{version}},prefix=frontend-
            type=semver,pattern={{major}}.{{minor}},prefix=frontend-
            type=semver,pattern={{major}},prefix=frontend-
          flavor: |
            latest=false

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Docker/Backend.docker
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.backend-meta.outputs.tags }}
          labels: ${{ steps.backend-meta.outputs.labels }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Docker/Frontend.docker
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.frontend-meta.outputs.tags }}
          labels: ${{ steps.frontend-meta.outputs.labels }}